version: '3'

services:
  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    volumes:
      - ./admin/:/admin/
      - /var/run/docker.sock:/var/run/docker.sock
    command: gunicorn admin.wsgi:application --reload -w 2 -b 0.0.0.0:8010
    
    env_file:
      - .env

    ports:
      - 8010:8010
    restart: "always"

    depends_on:
      - db
      - redis

  db:
      image: postgres:12.1-alpine
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      env_file:
        - .env
      ports:
        - 5434:5434
      environment:
        - POSTGRES_DB=bomach2
        - POSTGRES_user=bomach_user
        - POSTGRES_PASSWORD=odoo
      restart: "always"

  celery:
    build: ./admin

    command: celery -A admin worker -l info
    volumes:
      - ./admin/:/usr/src/app/
      
    depends_on:
      - redis

  celery-beat:
    build: ./admin
    command: celery -A admin beat -l info
    volumes:
      - ./admin/:/usr/src/app/

    depends_on:
      - redis
     
  redis:
    image: "redis:latest"
   
    expose:
      - 6379
    working_dir: /data
    volumes:
      - redis_data:/data
    restart: "always"

volumes:
  postgres_data:
  redis_data:

