# Generated by Django 4.1.5 on 2023-02-09 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authuser", "0003_branch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                error_messages="Email Already Taken",
                max_length=254,
                unique=True,
                verbose_name="email address",
            ),
        ),
    ]
