# Generated by Django 4.1.5 on 2023-02-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authuser", "0004_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="salutation",
            field=models.CharField(
                choices=[
                    ("---", "Choose"),
                    ("mr", "Mr"),
                    ("Mrs", "Mrs"),
                    ("miss", "Miss"),
                    ("dr", "Dr"),
                    ("sir", "Sir"),
                    ("madam", "Madam"),
                ],
                default="---",
                max_length=300,
            ),
        ),
    ]
