# Generated by Django 4.1.5 on 2023-02-19 18:22

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ("authuser", "0005_user_salutation"),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="branch_date",
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name="branch",
            name="country",
            field=django_countries.fields.CountryField(default="---", max_length=200),
        ),
        migrations.AddField(
            model_name="branch",
            name="no_of_staff",
            field=models.CharField(default="---", max_length=250),
        ),
        migrations.AddField(
            model_name="branch",
            name="office_address",
            field=models.CharField(default="---", max_length=250),
        ),
        migrations.AddField(
            model_name="branch",
            name="state",
            field=models.CharField(default="---", max_length=50, null=True),
        ),
        migrations.CreateModel(
            name="BranchAccessories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("image", models.CharField(max_length=150)),
                ("serial_number", models.CharField(max_length=150)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_branch",
                        to="authuser.branch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Branch Accessories",
                "verbose_name_plural": "Branch Accessories",
            },
        ),
    ]
