# Generated by Django 4.1.5 on 2023-03-01 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "authuser",
            "0006_branch_branch_date_branch_country_branch_no_of_staff_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="branchaccessories",
            name="assets_type",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="branchaccessories",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="branchaccessories",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("functioning", "Functioning"),
                    ("nonfunctioning", "Non Functioning"),
                ],
                max_length=150,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="branchaccessories",
            name="value_of_asset",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
