# Generated by Django 4.1.5 on 2023-03-02 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authuser", "0007_branchaccessories_assets_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="branchaccessories",
            name="image",
        ),
        migrations.AddField(
            model_name="branch",
            name="code",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="branchaccessories",
            name="code",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="branchaccessories",
            name="date_of_purchase",
            field=models.DateField(default="2023-06-10"),
        ),
    ]
