# Generated by Django 4.1.5 on 2023-03-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authuser", "0009_alter_branchaccessories_assets_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="branchaccessories",
            name="assets_type",
            field=models.CharField(
                blank=True, choices=[("assets", "Express")], max_length=150, null=True
            ),
        ),
    ]
