# Generated by Django 4.1.5 on 2023-03-07 17:51

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("authuser", "0016_alter_branchaccessories_value_of_asset_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="branchaccessories",
            name="value_of_asset",
            field=djmoney.models.fields.MoneyField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
