# Generated by Django 4.1.5 on 2023-03-08 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authuser", "0024_alter_branchaccessories_value_of_asset_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="branchaccessories",
            name="value_of_asset_currency",
        ),
        migrations.AlterField(
            model_name="branchaccessories",
            name="value_of_asset",
            field=models.CharField(max_length=500, null=True),
        ),
    ]
