# Generated by Django 4.1.5 on 2023-03-27 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authuser", "0026_branchaccessories_value_of_asset_currency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="surname",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
