# Generated by Django 4.1.5 on 2023-02-13 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "human_resource",
            "0002_department_employeetype_jobs_remove_employee_salary_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Designation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField()),
            ],
            options={
                "verbose_name": "Designation",
                "verbose_name_plural": "Designation",
            },
        ),
        migrations.AlterModelOptions(
            name="job_history",
            options={
                "verbose_name": "Job History",
                "verbose_name_plural": "Job Histories",
            },
        ),
        migrations.AlterModelOptions(
            name="jobs",
            options={"verbose_name": "Job", "verbose_name_plural": "Jobs"},
        ),
        migrations.AlterModelOptions(
            name="salary",
            options={"verbose_name": "Salaries", "verbose_name_plural": "Salary"},
        ),
        migrations.AlterField(
            model_name="employee",
            name="designation",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employee_designation_relationship",
                to="human_resource.designation",
            ),
        ),
    ]
