# Generated by Django 4.1.5 on 2023-02-13 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("human_resource", "0004_advert"),
    ]

    operations = [
        migrations.AddField(
            model_name="advert",
            name="is_stile_open",
            field=models.BooleanField(default=False),
        ),
    ]
