# Generated by Django 4.1.5 on 2023-02-13 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("human_resource", "0005_advert_is_stile_open"),
    ]

    operations = [
        migrations.RenameField(
            model_name="advert",
            old_name="is_stile_open",
            new_name="is_still_open",
        ),
    ]
