# Generated by Django 4.1.5 on 2023-02-13 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("human_resource", "0006_rename_is_stile_open_advert_is_still_open"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salary",
            name="paid_date",
            field=models.DateField(auto_now=True),
        ),
    ]
