# Generated by Django 4.1.5 on 2023-02-14 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("human_resource", "0007_alter_salary_paid_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="status",
            field=models.CharField(
                choices=[
                    ("proposed", "Proposed"),
                    ("retired", "Retired"),
                    ("probation", "On Probation"),
                ],
                default="proposed",
                max_length=250,
            ),
        ),
    ]
