# Generated by Django 4.1.5 on 2023-02-16 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("human_resource", "0010_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="end_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="task",
            name="start_date",
            field=models.DateField(),
        ),
    ]
