# Generated by Django 4.1.5 on 2023-02-16 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("human_resource", "0011_alter_task_end_date_alter_task_start_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="skill",
            name="department",
        ),
        migrations.RemoveField(
            model_name="skill",
            name="employee",
        ),
        migrations.AddField(
            model_name="employee",
            name="skills",
            field=models.ManyToManyField(
                blank=True, null=True, to="human_resource.skill"
            ),
        ),
        migrations.AddField(
            model_name="skill",
            name="description",
            field=models.TextField(default="----"),
        ),
    ]
