# Generated by Django 4.1.5 on 2023-02-16 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0008_remove_servicecategory_service_and_more"),
        (
            "human_resource",
            "0012_remove_skill_department_remove_skill_employee_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_service_category_relationship",
                to="settings.servicecategory",
            ),
        ),
    ]
