# Generated by Django 4.1.5 on 2023-02-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("human_resource", "0013_task_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="last_created",
            field=models.DateField(auto_now=True),
        ),
    ]
