# Generated by Django 4.1.5 on 2023-02-19 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("human_resource", "0014_employee_last_created"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="date_of_birth",
        ),
    ]
