# Generated by Django 4.1.5 on 2023-02-19 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("human_resource", "0015_remove_employee_date_of_birth"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="date_of_birth",
            field=models.DateField(auto_now=True),
        ),
    ]
