# Generated by Django 4.1.5 on 2023-02-19 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("human_resource", "0016_employee_date_of_birth"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employee",
            old_name="date_of_birth",
            new_name="dob",
        ),
    ]
