# Generated by Django 4.1.5 on 2023-02-20 00:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("human_resource", "0017_rename_date_of_birth_employee_dob"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="salary",
            field=models.CharField(default="---", max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="dob",
            field=models.DateField(default="2023-04-01"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hr_employee_relationship",
                to=settings.AUTH_USER_MODEL,
                verbose_name="employee",
            ),
        ),
    ]
