# Generated by Django 4.1.5 on 2023-02-20 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("human_resource", "0018_employee_salary_alter_employee_dob_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="jobs",
            options={"verbose_name": "Roles", "verbose_name_plural": "Roles"},
        ),
        migrations.RemoveField(
            model_name="jobs",
            name="job_title",
        ),
        migrations.RemoveField(
            model_name="jobs",
            name="max_salary",
        ),
        migrations.RemoveField(
            model_name="jobs",
            name="min_salary",
        ),
        migrations.AddField(
            model_name="jobs",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hr_employee_relationship",
                to="human_resource.employee",
            ),
        ),
    ]
