# Generated by Django 4.1.5 on 2023-02-20 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "authuser",
            "0006_branch_branch_date_branch_country_branch_no_of_staff_and_more",
        ),
        ("human_resource", "0019_alter_jobs_options_remove_jobs_job_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hr_branch_employee_relationship",
                to="authuser.branch",
                verbose_name="branch",
            ),
        ),
    ]
