# Generated by Django 4.1.5 on 2023-02-26 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("human_resource", "0020_employee_branch"),
    ]

    operations = [
        migrations.AddField(
            model_name="advert",
            name="code",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="department",
            name="code",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="code",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="job_history",
            name="code",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="jobs",
            name="code",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="salary",
            name="code",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="skill",
            name="code",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="code",
            field=models.CharField(max_length=150, null=True),
        ),
    ]
