# Generated by Django 4.1.5 on 2023-03-07 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("authuser", "0008_remove_branchaccessories_image_branch_code_and_more"),
        ("human_resource", "0021_advert_code_department_code_employee_code_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="jobs",
            options={"verbose_name": "Job Roles", "verbose_name_plural": "Roles"},
        ),
        migrations.AddField(
            model_name="jobs",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="authuser.branch",
            ),
        ),
    ]
