# Generated by Django 4.1.5 on 2023-03-07 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("authuser", "0008_remove_branchaccessories_image_branch_code_and_more"),
        ("human_resource", "0022_alter_jobs_options_jobs_branch"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="jobs",
            options={"verbose_name": "Job Role", "verbose_name_plural": "Job Roles"},
        ),
        migrations.AddField(
            model_name="salary",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="authuser.branch",
            ),
        ),
        migrations.AddField(
            model_name="salary",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="employee",
            ),
        ),
    ]
