# Generated by Django 4.1.5 on 2023-03-07 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("human_resource", "0023_alter_jobs_options_salary_branch_salary_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobs",
            name="employee",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hr_employee_relationship",
                to="human_resource.employee",
            ),
        ),
    ]
