# Generated by Django 4.1.5 on 2023-03-07 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("human_resource", "0024_alter_jobs_employee"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="salary",
            name="amount",
        ),
    ]
