# Generated by Django 4.1.5 on 2023-03-07 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("human_resource", "0026_salary_amount_salary_amount_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salary",
            name="reduction",
            field=models.CharField(default=0, max_length=150),
        ),
    ]
