# Generated by Django 4.1.5 on 2023-03-07 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("human_resource", "0027_alter_salary_reduction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salary",
            name="reduction",
            field=models.CharField(blank=True, default=0, max_length=150, null=True),
        ),
    ]
