# Generated by Django 4.1.5 on 2023-03-09 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("human_resource", "0028_alter_salary_reduction"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobs",
            name="employee",
        ),
        migrations.AddField(
            model_name="designation",
            name="roles",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="designation_roles",
                to="human_resource.jobs",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="special_roles",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="employee_roles",
                to="human_resource.jobs",
            ),
        ),
        migrations.AddField(
            model_name="jobs",
            name="name",
            field=models.CharField(max_length=150, null=True),
        ),
    ]
