# Generated by Django 4.1.5 on 2023-03-09 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("human_resource", "0029_remove_jobs_employee_designation_roles_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="designation",
            name="roles",
            field=models.ManyToManyField(
                blank=True, related_name="designation_roles", to="human_resource.jobs"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="special_roles",
            field=models.ManyToManyField(
                blank=True, related_name="employee_roles", to="human_resource.jobs"
            ),
        ),
    ]
