# Generated by Django 4.1.5 on 2023-03-09 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("human_resource", "0030_alter_designation_roles_alter_employee_special_roles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="designation",
            name="roles",
            field=models.ManyToManyField(blank=True, to="human_resource.jobs"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="special_roles",
            field=models.ManyToManyField(blank=True, to="human_resource.jobs"),
        ),
    ]
