# Generated by Django 4.1.5 on 2023-03-09 15:52

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("human_resource", "0031_alter_designation_roles_alter_employee_special_roles"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobs",
            name="branch",
        ),
        migrations.AlterField(
            model_name="jobs",
            name="description",
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
