# Generated by Django 4.1.5 on 2023-03-09 16:07

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("human_resource", "0032_remove_jobs_branch_alter_jobs_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobs",
            name="description",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
