# Generated by Django 4.1.5 on 2023-03-09 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("human_resource", "0033_alter_jobs_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="designation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="human_resource.designation",
            ),
        ),
        migrations.AlterField(
            model_name="jobs",
            name="name",
            field=models.CharField(max_length=150, null=True, verbose_name="Title"),
        ),
    ]
