# Generated by Django 4.1.5 on 2023-03-10 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("human_resource", "0034_skill_designation_alter_jobs_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skill",
            name="name",
            field=models.CharField(max_length=150, verbose_name="Title"),
        ),
    ]
