# Generated by Django 4.1.5 on 2023-03-10 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("human_resource", "0035_alter_skill_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="skills",
            field=models.ManyToManyField(blank=True, to="human_resource.skill"),
        ),
    ]
