# Generated by Django 4.1.5 on 2023-03-13 17:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0017_delete_activities"),
        ("authuser", "0026_branchaccessories_value_of_asset_currency_and_more"),
        ("human_resource", "0036_alter_employee_skills"),
    ]

    operations = [
        migrations.CreateModel(
            name="DrawingBank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=200)),
                ("title", models.CharField(max_length=150)),
                ("description", models.TextField()),
                ("created", models.DateField(auto_now=True)),
            ],
            options={
                "verbose_name": "Drawing Bank",
                "verbose_name_plural": "Drawing Bank",
            },
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=150)),
                ("phone", models.CharField(max_length=150)),
                ("message", models.TextField()),
                ("appointment_time", models.TimeField(default="00:00:00")),
                (
                    "appointment_date",
                    models.DateField(default=django.utils.timezone.now),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointment_rel",
                        to="authuser.branch",
                    ),
                ),
                (
                    "service_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointment_service_rel",
                        to="settings.servicecategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Appointment",
                "verbose_name_plural": "Appointments",
            },
        ),
    ]
