# Generated by Django 4.1.5 on 2023-03-18 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("human_resource", "0037_drawingbank_appointment"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Appointment",
        ),
    ]
