# Generated by Django 4.1.5 on 2023-03-25 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("human_resource", "0038_delete_appointment"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DrawingBank",
        ),
    ]
