# Generated by Django 4.1.5 on 2023-02-21 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0008_alter_customer_country"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reportpayment",
            name="model_id",
        ),
        migrations.RemoveField(
            model_name="reportpayment",
            name="model_id_name",
        ),
        migrations.RemoveField(
            model_name="reportpayment",
            name="modelname",
        ),
        migrations.AddField(
            model_name="reportpayment",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="report_author_payment",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="reportpayment",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="report_client",
                to="customer.customer",
                verbose_name="Client",
            ),
        ),
        migrations.AddField(
            model_name="reportpayment",
            name="total_amount",
            field=models.CharField(max_length=150, null=True),
        ),
    ]
