# Generated by Django 4.1.5 on 2023-02-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0002_remove_reportpayment_model_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportpayment",
            name="created_at",
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name="reportpayment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("sold", "Sold"),
                    ("reserve", "Reserved"),
                ],
                default="pending",
                max_length=500,
                null=True,
            ),
        ),
    ]
