# Generated by Django 4.1.5 on 2023-02-22 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0003_reportpayment_created_at_reportpayment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportpayment",
            name="code",
            field=models.CharField(max_length=150, null=True),
        ),
    ]
