# Generated by Django 4.1.5 on 2023-03-10 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0004_reportpayment_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportingSheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.CharField(max_length=150, null=True)),
                ("report_type", models.CharField(max_length=150, null=True)),
                ("created_at", models.DateField(auto_now=True)),
            ],
            options={
                "verbose_name": "All Reporting",
                "verbose_name_plural": "Reporting",
            },
        ),
    ]
