# Generated by Django 4.1.5 on 2023-03-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0005_reportingsheet"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportingsheet",
            name="modelid",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="reportingsheet",
            name="modelname",
            field=models.CharField(max_length=250, null=True),
        ),
    ]
