# Generated by Django 4.1.5 on 2023-04-21 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0007_landsurveyreport_generalreport_engineeringreport"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="engineeringreport",
            options={
                "permissions": (
                    ("can_perform_extra_action", "Can perform extra action"),
                ),
                "verbose_name": "Engineering Report",
                "verbose_name_plural": "Engineering Reports",
            },
        ),
        migrations.AlterField(
            model_name="engineeringreport",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accept"),
                    ("rejected", "Reject"),
                ],
                default="pending",
                max_length=150,
            ),
        ),
    ]
