# Generated by Django 4.1.5 on 2023-04-22 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0008_alter_engineeringreport_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="engineeringreport",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accept"),
                    ("rejected", "Reject"),
                    ("cancelled", "cancelled"),
                ],
                default="pending",
                max_length=150,
            ),
        ),
    ]
