# Generated by Django 4.1.5 on 2023-04-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0010_engineeringreport_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="generalreport",
            options={
                "verbose_name": "General Report",
                "verbose_name_plural": "General Report",
            },
        ),
        migrations.AddField(
            model_name="generalreport",
            name="code",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="generalreport",
            name="report_title",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="generalreport",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("incomplete", "Incomplete"),
                    ("to_do", "To Do"),
                    ("redo", "Redo"),
                    ("doing", "Doing"),
                    ("completed", "Completed"),
                ],
                default="pending",
                max_length=150,
            ),
        ),
    ]
