# Generated by Django 4.1.5 on 2023-04-22 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0009_customer_code"),
        ("reports", "0012_generalreport_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="landsurveyreport",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="customer.customer",
            ),
        ),
    ]
