# Generated by Django 4.1.5 on 2023-01-31 02:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
