# Generated by Django 4.1.5 on 2023-02-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0002_employee_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="name",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="year",
        ),
        migrations.AddField(
            model_name="employee",
            name="Skills",
            field=models.CharField(default="---", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="about",
            field=models.TextField(default="---"),
        ),
        migrations.AddField(
            model_name="employee",
            name="address",
            field=models.CharField(default="---", max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="country",
            field=models.CharField(default="---", max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="create_at",
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="date_of_birth",
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="department",
            field=models.CharField(
                choices=[
                    ("marketing", "Marketing"),
                    ("sales", "Sales"),
                    ("humanresources", "Human Resources"),
                    ("publicrelations", "Public Relations"),
                    ("research", "Research"),
                    ("financeandAccounts", "finance and Accounts"),
                    ("operations", "Operations"),
                ],
                default="---",
                max_length=250,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="designation",
            field=models.CharField(
                choices=[
                    ("trainee", "Trainee"),
                    ("senior", "Senior"),
                    ("junior", "Junior"),
                    ("teamlead", "Team lead"),
                    ("adhoc", "Adhoc"),
                ],
                default="---",
                max_length=250,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="employment_type",
            field=models.CharField(
                choices=[
                    ("marketing", "Marketing"),
                    ("sales", "Sales"),
                    ("humanresources", "Human Resources"),
                    ("publicrelations", "Public Relations"),
                    ("research", "Research"),
                    ("financeandAccounts", "finance and Accounts"),
                    ("operations", "Operations"),
                ],
                default="---",
                max_length=250,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female"), ("others", "Others")],
                default="---",
                max_length=250,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="local_government",
            field=models.CharField(default="---", max_length=250),
        ),
        migrations.AddField(
            model_name="employee",
            name="marital_status",
            field=models.CharField(
                choices=[
                    ("single", "Single"),
                    ("married", "Married"),
                    ("divorced", "Divorced"),
                ],
                default="---",
                max_length=250,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="phone_number",
            field=models.CharField(default="---", max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="probation_end_date",
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="probation_start_date",
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="salary",
            field=models.CharField(default="---", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="start_date",
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="title",
            field=models.CharField(
                choices=[
                    ("civilengineer", "Civil Engineer"),
                    ("landsurveyor", "Land Surveyor"),
                    ("marketer", "Marketer"),
                    ("developer", "Developer"),
                    ("secretary", "Secretary"),
                    ("consultants", "Consultants"),
                    ("chiefsecurityofficer", "Chief Security Officer"),
                    ("securityofficer", "Security Officer"),
                    ("technician", "Technician"),
                ],
                default="---",
                max_length=250,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="town",
            field=models.CharField(default="---", max_length=250, null=True),
        ),
    ]
