# Generated by Django 4.1.5 on 2023-02-11 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0005_alter_employee_country"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employee",
            old_name="Skills",
            new_name="skills",
        ),
    ]
