# Generated by Django 4.1.5 on 2023-02-13 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0006_rename_skills_employee_skills"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="state",
            field=models.CharField(default="---", max_length=50, null=True),
        ),
    ]
