# Generated by Django 4.1.5 on 2023-02-03 22:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("realestate", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="realestate",
            name="branch",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_branch_rel",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Choose Branch",
            ),
        ),
    ]
