# Generated by Django 4.1.5 on 2023-01-31 02:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("realestate", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="realestate",
            name="year",
        ),
        migrations.AddField(
            model_name="realestate",
            name="amount_deposited",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="realestate",
            name="content",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="realestate",
            name="created_at",
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name="realestate",
            name="development_fee",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="realestate",
            name="is_blocked",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name="realestate",
            name="is_featured",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name="realestate",
            name="is_frontend",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name="realestate",
            name="legal_fee",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="realestate",
            name="survey_plan",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="realestate",
            name="total_amount",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="realestate",
            name="unique_code",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="realestate",
            name="unit_price",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="realestate",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name="realestate",
            name="name",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.CreateModel(
            name="RealEstatePlot",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=500, null=True)),
                ("price", models.CharField(max_length=500, null=True)),
                ("size", models.CharField(max_length=500, null=True)),
                ("status", models.CharField(max_length=500, null=True)),
                ("content", models.CharField(max_length=500, null=True)),
                ("timer_date", models.CharField(max_length=500, null=True)),
                ("timer", models.CharField(max_length=500, null=True)),
                ("transactional_code", models.CharField(max_length=500, null=True)),
                ("purchase_code", models.CharField(max_length=500, null=True)),
                ("unique_code", models.CharField(max_length=500, null=True)),
                ("resell_code", models.CharField(max_length=500, null=True)),
                ("payment_id", models.CharField(max_length=500, null=True)),
                ("is_blocked", models.BooleanField(default=False, null=True)),
                ("is_featured", models.BooleanField(default=False, null=True)),
                ("is_frontend", models.BooleanField(default=False, null=True)),
                ("is_sold", models.BooleanField(default=False, null=True)),
                (
                    "realestate",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="realestate_rel",
                        to="realestate.realestate",
                        verbose_name="Realestate",
                    ),
                ),
            ],
        ),
    ]
