# Generated by Django 4.1.5 on 2023-01-31 02:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        (
            "realestate",
            "0002_remove_realestate_year_realestate_amount_deposited_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="realestate",
            name="id",
        ),
        migrations.AlterField(
            model_name="realestate",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
    ]
