# Generated by Django 4.1.5 on 2023-01-31 02:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("realestate", "0003_remove_realestate_id_alter_realestate_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="realestate",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
