# Generated by Django 4.1.5 on 2023-02-04 00:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("realestate", "0003_realestate_user_alter_realestate_branch"),
    ]

    operations = [
        migrations.AddField(
            model_name="realestateplot",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_realestate_plot_rel",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
