# Generated by Django 4.1.5 on 2023-02-04 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("realestate", "0006_alter_realestateplot_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="realestate",
            name="status",
            field=models.CharField(
                choices=[
                    ("soldout", "Completedly Soldout"),
                    ("avaliable", "Can Still Sell Plots"),
                ],
                default="avaliable",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="realestateplot",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("sold", "Sold"),
                    ("reserved", "Reserved"),
                ],
                default="pending",
                max_length=500,
                null=True,
            ),
        ),
    ]
