# Generated by Django 4.1.5 on 2023-02-08 05:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("realestate", "0007_realestate_status_alter_realestateplot_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sold", "Sold"),
                            ("reserve", "Reserved"),
                        ],
                        default="pending",
                        max_length=500,
                        null=True,
                    ),
                ),
                ("activation_code", models.CharField(max_length=500, null=True)),
                ("customer_email", models.CharField(max_length=500, null=True)),
                ("customer", models.CharField(max_length=500, null=True)),
                ("initial_amount", models.CharField(max_length=500, null=True)),
                ("is_blocked", models.BooleanField(default=False, null=True)),
                ("limited_date", models.DateField(null=True)),
                ("created_at", models.DateField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="realestate_payment",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
