# Generated by Django 4.1.5 on 2023-02-08 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("realestate", "0011_alter_realestatepayment_limited_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="realestatepayment",
            name="limited_date",
            field=models.DateField(blank=True, default="1992-01-01", null=True),
        ),
    ]
