# Generated by Django 4.1.5 on 2023-02-10 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("realestate", "0023_realestatepayment_customer_phone_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentConfirmationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activation_link", models.CharField(max_length=500, null=True)),
                ("is_payment_activated", models.BooleanField(default=False, null=True)),
                ("created_at", models.DateField(auto_now=True)),
                (
                    "payment",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="realestate_payment_confirmation",
                        to="realestate.realestatepayment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Request",
                "verbose_name_plural": "Confirmation Request",
                "managed": True,
            },
        ),
    ]
