# Generated by Django 4.1.5 on 2023-02-10 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("realestate", "0025_paymentconfirmationrequest_activation_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentconfirmationrequest",
            name="activation_link_code",
            field=models.CharField(max_length=500, null=True),
        ),
    ]
