# Generated by Django 4.1.5 on 2023-02-10 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("realestate", "0027_paymentconfirmationrequest_last_modified_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="realestatepayment",
            name="wait_confirmation",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
