# Generated by Django 4.1.5 on 2023-02-11 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("realestate", "0028_realestatepayment_wait_confirmation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="paymentconfirmationrequest",
            options={
                "managed": True,
                "verbose_name": "Payment Request",
                "verbose_name_plural": "Payment Request",
            },
        ),
        migrations.AlterModelOptions(
            name="realestatepayment",
            options={"verbose_name_plural": "Payment"},
        ),
    ]
