# Generated by Django 4.1.5 on 2023-02-21 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("realestate", "0029_alter_paymentconfirmationrequest_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="realestatepayment",
            name="user",
        ),
    ]
