# Generated by Django 4.1.5 on 2023-02-21 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("realestate", "0030_remove_realestatepayment_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="realestatepayment",
            name="total_amount",
        ),
    ]
