# Generated by Django 4.1.5 on 2023-02-21 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0002_remove_reportpayment_model_id_and_more"),
        ("realestate", "0031_remove_realestatepayment_total_amount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="realestatepayment",
            name="id",
        ),
        migrations.AddField(
            model_name="realestatepayment",
            name="reportpayment_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default=20,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="reports.reportpayment",
            ),
            preserve_default=False,
        ),
    ]
