# Generated by Django 4.1.5 on 2023-02-21 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("realestate", "0032_remove_realestatepayment_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="realestatepayment",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="realestatepayment",
            name="status",
        ),
    ]
