# Generated by Django 4.1.5 on 2023-02-26 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("realestate", "0033_remove_realestatepayment_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="realestate",
            name="code",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="realestateplot",
            name="code",
            field=models.CharField(max_length=150, null=True),
        ),
    ]
