# Generated by Django 4.1.5 on 2023-03-08 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("realestate", "0037_alter_realestate_development_fee_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="realestate",
            name="development_fee_currency",
        ),
        migrations.RemoveField(
            model_name="realestate",
            name="legal_fee_currency",
        ),
        migrations.RemoveField(
            model_name="realestate",
            name="unit_price_currency",
        ),
        migrations.RemoveField(
            model_name="realestateplot",
            name="price_currency",
        ),
        migrations.AlterField(
            model_name="realestate",
            name="development_fee",
            field=models.CharField(default=0.01, max_length=500),
        ),
        migrations.AlterField(
            model_name="realestate",
            name="legal_fee",
            field=models.CharField(default=0.01, max_length=500),
        ),
        migrations.AlterField(
            model_name="realestate",
            name="unit_price",
            field=models.CharField(default=0.01, max_length=500),
        ),
        migrations.AlterField(
            model_name="realestateplot",
            name="price",
            field=models.CharField(default=0.01, max_length=500),
        ),
    ]
