# Generated by Django 4.1.5 on 2023-02-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0003_alter_customer_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="name",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="year",
        ),
        migrations.AddField(
            model_name="customer",
            name="country",
            field=models.CharField(default="---", max_length=50),
        ),
        migrations.AddField(
            model_name="customer",
            name="create_at",
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="current_address",
            field=models.CharField(default="---", max_length=50),
        ),
        migrations.AddField(
            model_name="customer",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female"), ("others", "Others")],
                default="---",
                max_length=250,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="local_government",
            field=models.CharField(default="---", max_length=50),
        ),
        migrations.AddField(
            model_name="customer",
            name="notes",
            field=models.TextField(default="---"),
        ),
        migrations.AddField(
            model_name="customer",
            name="permanent_address",
            field=models.CharField(default="---", max_length=50),
        ),
        migrations.AddField(
            model_name="customer",
            name="phone",
            field=models.CharField(default="---", max_length=50),
        ),
        migrations.AddField(
            model_name="customer",
            name="state",
            field=models.CharField(default="---", max_length=50),
        ),
        migrations.AddField(
            model_name="customer",
            name="town",
            field=models.CharField(default="---", max_length=50),
        ),
    ]
