# Generated by Django 4.1.5 on 2023-02-11 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0004_remove_customer_name_remove_customer_year_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="country",
            field=models.CharField(default="---", max_length=250),
        ),
    ]
