# Generated by Django 4.1.5 on 2023-02-11 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0005_alter_customer_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="country",
            field=models.CharField(default="---", max_length=200),
        ),
        migrations.AlterField(
            model_name="customer",
            name="current_address",
            field=models.CharField(default="---", max_length=200),
        ),
        migrations.AlterField(
            model_name="customer",
            name="local_government",
            field=models.CharField(default="---", max_length=200),
        ),
        migrations.AlterField(
            model_name="customer",
            name="permanent_address",
            field=models.CharField(default="---", max_length=200),
        ),
        migrations.AlterField(
            model_name="customer",
            name="phone",
            field=models.CharField(default="---", max_length=200),
        ),
        migrations.AlterField(
            model_name="customer",
            name="state",
            field=models.CharField(default="---", max_length=200),
        ),
        migrations.AlterField(
            model_name="customer",
            name="town",
            field=models.CharField(default="---", max_length=200),
        ),
    ]
