# Generated by Django 4.1.5 on 2023-02-11 21:45

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0007_alter_customer_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="country",
            field=django_countries.fields.CountryField(default="---", max_length=250),
        ),
    ]
