# Generated by Django 4.1.5 on 2023-01-31 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tasks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="name")),
                ("year", models.DateField(auto_now_add=True, verbose_name="Year")),
                ("task_title", models.CharField(max_length=255, null=True)),
                ("priority", models.CharField(max_length=500, null=True)),
                ("start_date", models.CharField(max_length=500, null=True)),
                ("end_date", models.CharField(max_length=500, null=True)),
            ],
            options={
                "verbose_name": "Tasks",
                "verbose_name_plural": "Tasks",
            },
        ),
    ]
