# Generated by Django 4.1.5 on 2023-01-31 02:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0002_tasks_uuid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tasks",
            name="id",
        ),
        migrations.AlterField(
            model_name="tasks",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
    ]
