# Generated by Django 4.1.5 on 2023-02-04 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("realestate", "0004_realestateplot_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="realestateplot",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
