# Generated by Django 4.1.5 on 2023-02-08 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("realestate", "0009_rename_payment_realestatepayment"),
    ]

    operations = [
        migrations.AddField(
            model_name="realestatepayment",
            name="plot",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="realestate_payment_plot",
                to="realestate.realestateplot",
            ),
        ),
    ]
