# Generated by Django 4.1.5 on 2023-02-08 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("realestate", "0014_alter_realestatepayment_limited_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="realestateplot",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("sold", "Sold"),
                    ("reserved", "Reserved"),
                ],
                default="available",
                max_length=500,
                null=True,
            ),
        ),
    ]
