# Generated by Django 4.1.5 on 2023-02-09 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("realestate", "0016_realestatepayment_is_new_customer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="realestateplot",
            name="payment_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="realestate_payment_id_plot",
                to="realestate.realestatepayment",
            ),
        ),
    ]
