# Generated by Django 4.1.5 on 2023-02-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("realestate", "0018_realestatepayment_is_payment_activated_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="realestatepayment",
            name="total_amount",
            field=models.CharField(max_length=250, null=True),
        ),
    ]
