# Generated by Django 4.1.5 on 2023-02-09 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("realestate", "0019_realestatepayment_total_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="realestatepayment",
            name="proxy",
            field=models.CharField(max_length=250, null=True),
        ),
    ]
