# Generated by Django 4.1.5 on 2023-02-09 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("realestate", "0022_realestatepayment_third_party_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="realestatepayment",
            name="customer_phone",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="realestatepayment",
            name="is_confirmed",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
