# Generated by Django 4.1.5 on 2023-02-10 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("realestate", "0026_paymentconfirmationrequest_activation_link_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentconfirmationrequest",
            name="last_modified",
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name="paymentconfirmationrequest",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_confirmation_payment",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
