# Generated by Django 4.1.5 on 2023-02-14 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("size", models.CharField(max_length=150)),
                ("url", models.CharField(max_length=250, null=True)),
                ("filesize", models.CharField(max_length=250, null=True)),
                ("filename", models.CharField(max_length=250, null=True)),
                ("object_name", models.CharField(max_length=250, null=True)),
            ],
            options={
                "verbose_name": "Gallery",
                "verbose_name_plural": "Gallery",
            },
        ),
    ]
