# Generated by Django 4.1.5 on 2023-02-14 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gallery",
            name="filename",
        ),
        migrations.RemoveField(
            model_name="gallery",
            name="filesize",
        ),
        migrations.RemoveField(
            model_name="gallery",
            name="object_name",
        ),
        migrations.AddField(
            model_name="gallery",
            name="created_at",
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name="gallery",
            name="data",
            field=models.TextField(default=""),
        ),
    ]
