# Generated by Django 4.1.5 on 2023-02-14 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0002_remove_gallery_filename_remove_gallery_filesize_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gallery",
            name="filename",
            field=models.CharField(default="", max_length=150),
        ),
        migrations.AddField(
            model_name="gallery",
            name="type",
            field=models.CharField(default="", max_length=150),
        ),
    ]
