# Generated by Django 4.1.5 on 2023-02-14 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0003_gallery_filename_gallery_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gallery",
            name="data",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
