# Generated by Django 4.1.5 on 2023-02-16 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0006_service_servicecategory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="servicecategory",
            name="service",
        ),
        migrations.AddField(
            model_name="servicecategory",
            name="service",
            field=models.ManyToManyField(to="settings.service"),
        ),
    ]
