# Generated by Django 4.1.5 on 2023-02-16 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0007_remove_servicecategory_service_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="servicecategory",
            name="service",
        ),
        migrations.AddField(
            model_name="servicecategory",
            name="service",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hr_service_relationship",
                to="settings.service",
            ),
        ),
    ]
