# Generated by Django 4.1.5 on 2023-02-21 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0009_remove_gallery_data_remove_gallery_filename_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GalleryTest",
            fields=[
                (
                    "gallery_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="settings.gallery",
                    ),
                ),
            ],
            options={
                "verbose_name": "GalleryTest",
                "verbose_name_plural": "GalleryTest",
            },
            bases=("settings.gallery",),
        ),
    ]
