# Generated by Django 4.1.5 on 2023-02-21 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0011_gallerytest_is_paid"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GalleryTest",
        ),
    ]
