# Generated by Django 4.1.5 on 2023-03-07 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("authuser", "0008_remove_branchaccessories_image_branch_code_and_more"),
        ("settings", "0012_delete_gallerytest"),
    ]

    operations = [
        migrations.CreateModel(
            name="Types",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("assets", "Assets (Type)")], max_length=150
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("created", models.DateField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="types_branch_rel",
                        to="authuser.branch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Type",
                "verbose_name_plural": "Types",
            },
        ),
    ]
