# Generated by Django 4.1.5 on 2023-03-07 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0013_types"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="types",
            name="branch",
        ),
    ]
