# Generated by Django 4.1.5 on 2023-03-10 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0014_remove_types_branch"),
    ]

    operations = [
        migrations.CreateModel(
            name="Activities",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
            ],
            options={
                "verbose_name": "Activities",
                "verbose_name_plural": "Activities",
            },
        ),
    ]
