# Generated by Django 4.1.5 on 2023-03-10 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0027_alter_engineeringreport_labor_and_bill_and_more"),
        ("settings", "0016_laborbillquotation_quotation"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Activities",
        ),
    ]
