# Generated by Django 4.1.5 on 2023-03-15 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0017_delete_activities"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="is_child_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="child_service_model",
                to="settings.service",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="parent_to",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service_parent_rel",
                to="settings.service",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Audio", (("vinyl", "Vinyl"), ("cd", "CD"))),
                    ("Video", (("vhs", "VHS Tape"), ("dvd", "DVD"))),
                    ("unknown", "Unknown"),
                ],
                max_length=150,
                null=True,
            ),
        ),
    ]
