# Generated by Django 4.1.5 on 2023-03-15 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0018_service_is_child_to_service_parent_to_service_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("ategory", (("category1", "Category1"),))],
                max_length=150,
                null=True,
            ),
        ),
    ]
