# Generated by Django 4.1.5 on 2023-03-15 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0019_alter_service_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("child", "Child"), ("parent", "Parent")],
                default="parent",
                max_length=150,
                null=True,
            ),
        ),
    ]
