# Generated by Django 4.1.5 on 2023-03-15 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0020_alter_service_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
