# Generated by Django 4.1.5 on 2023-03-15 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0021_alter_service_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceCalculator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("up", models.IntegerField(default=0, verbose_name="unit price")),
                (
                    "ebb",
                    models.IntegerField(default=0, verbose_name="Extra Below Price"),
                ),
                (
                    "efb",
                    models.IntegerField(default=0, verbose_name="Extra floor bill"),
                ),
                (
                    "nb",
                    models.IntegerField(default=0, verbose_name="Number of bedroom"),
                ),
                ("nf", models.IntegerField(default=0, verbose_name="Number of floor")),
                (
                    "mncb",
                    models.IntegerField(
                        default=0, verbose_name="Maximum number of category bedroom"
                    ),
                ),
                (
                    "mncf",
                    models.IntegerField(
                        default=0, verbose_name="Maximum number of category floor"
                    ),
                ),
            ],
            options={
                "verbose_name": "Services Calculator",
                "verbose_name_plural": "Service Calculator",
            },
        ),
    ]
