# Generated by Django 4.1.5 on 2023-03-15 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0022_servicecalculator"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicecalculator",
            name="service",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="settings.service",
            ),
        ),
    ]
