# Generated by Django 4.1.5 on 2023-03-15 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0023_servicecalculator_service"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicecalculator",
            name="ebb",
            field=models.IntegerField(
                default=0, verbose_name="Extra bedroom unit Price"
            ),
        ),
    ]
