# Generated by Django 4.1.5 on 2023-03-15 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0024_alter_servicecalculator_ebb"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicecalculator",
            name="name",
            field=models.CharField(max_length=150, null=True, verbose_name="Title"),
        ),
    ]
