# Generated by Django 4.1.5 on 2023-03-23 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0025_servicecalculator_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="laborbillquotation",
            name="qty_currency",
        ),
        migrations.AlterField(
            model_name="laborbillquotation",
            name="activity",
            field=models.CharField(
                max_length=150, null=True, verbose_name="Activity/Descriptions"
            ),
        ),
        migrations.AlterField(
            model_name="laborbillquotation",
            name="qty",
            field=models.IntegerField(null=True, verbose_name="Quantity"),
        ),
        migrations.AlterField(
            model_name="service",
            name="is_child_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="child_service_model",
                to="settings.service",
                verbose_name="Child",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="parent_to",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service_parent_rel",
                to="settings.service",
                verbose_name="Parent",
            ),
        ),
    ]
