# Generated by Django 4.1.5 on 2023-03-23 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0026_remove_laborbillquotation_qty_currency_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quotation",
            name="qty_currency",
        ),
        migrations.AlterField(
            model_name="laborbillquotation",
            name="name",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="quotation",
            name="name",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="quotation",
            name="qty",
            field=models.IntegerField(null=True, verbose_name="Quantity"),
        ),
    ]
