# Generated by Django 4.1.5 on 2023-03-25 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0027_remove_quotation_qty_currency_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="laborbillquotation",
            name="qty",
            field=models.FloatField(null=True, verbose_name="Quantity"),
        ),
    ]
