# Generated by Django 4.1.5 on 2023-03-25 17:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0028_alter_laborbillquotation_qty"),
    ]

    operations = [
        migrations.AddField(
            model_name="laborbillquotation",
            name="code",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="laborbillquotation",
            name="date_time",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name="quotation",
            name="code",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
