# Generated by Django 4.1.5 on 2023-03-25 17:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "settings",
            "0029_laborbillquotation_code_laborbillquotation_date_time_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="laborbillquotation",
            name="date_time",
            field=models.CharField(default=datetime.datetime.now, max_length=150),
        ),
    ]
