# Generated by Django 4.1.5 on 2023-03-25 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0030_alter_laborbillquotation_date_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="laborbillquotation",
            name="date_time",
            field=models.CharField(default="", max_length=150),
        ),
    ]
