# Generated by Django 4.1.5 on 2023-04-10 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0031_alter_laborbillquotation_date_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicecalculator",
            name="function",
            field=models.CharField(
                blank=True,
                choices=[("function1", "Function1")],
                help_text="Choose a function to calculate with!",
                max_length=150,
                null=True,
            ),
        ),
    ]
