# Generated by Django 4.1.5 on 2023-04-10 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0032_servicecalculator_function"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicecalculator",
            name="total",
            field=models.IntegerField(default=0),
        ),
    ]
