# Generated by Django 4.1.5 on 2023-04-12 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0033_servicecalculator_total"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicecalculator",
            name="function",
            field=models.CharField(
                blank=True,
                choices=[
                    ("function1", "Function1"),
                    ("general_engine_calc", "General Engine Calculator"),
                ],
                help_text="Choose a function to calculate with!",
                max_length=150,
                null=True,
            ),
        ),
    ]
