# Generated by Django 4.1.5 on 2023-04-22 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0035_servicecalculator_esrup_servicecalculator_mncs_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="quotation",
            old_name="unity_price",
            new_name="unit_price",
        ),
        migrations.RenameField(
            model_name="quotation",
            old_name="unity_price_currency",
            new_name="unit_price_currency",
        ),
    ]
