# Generated by Django 4.1.5 on 2023-02-20 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("human_resource", "0020_employee_branch"),
    ]

    operations = [
        migrations.CreateModel(
            name="OperationContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=150, null=True)),
                ("created_at", models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="OperationProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=150, null=True)),
                ("created_at", models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="OperationSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=150, null=True)),
                ("created_at", models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="OperationTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_category",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("task_title", models.CharField(max_length=150)),
                ("task_project", models.CharField(max_length=150)),
                ("task_site", models.CharField(max_length=150)),
                ("start_date", models.DateField(default="2023-05-01")),
                ("end_date", models.DateField(default="2023-05-01")),
                (
                    "task_priority",
                    models.CharField(
                        choices=[
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        max_length=150,
                    ),
                ),
                ("task_description", models.TextField()),
                ("is_done", models.BooleanField(default=False)),
                ("created_at", models.DateField(auto_now=True)),
                (
                    "assign_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operations_task_employee",
                        to="human_resource.employee",
                    ),
                ),
            ],
        ),
    ]
