# Generated by Django 4.1.5 on 2023-02-20 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="operationcontract",
            options={"verbose_name": "Contract", "verbose_name_plural": "Contracts"},
        ),
        migrations.AlterModelOptions(
            name="operationproject",
            options={"verbose_name": "Project", "verbose_name_plural": "Projects"},
        ),
        migrations.AlterModelOptions(
            name="operationsite",
            options={"verbose_name": "Site", "verbose_name_plural": "Sites"},
        ),
        migrations.AlterModelOptions(
            name="operationtask",
            options={"verbose_name": "Task", "verbose_name_plural": "Tasks"},
        ),
        migrations.AlterField(
            model_name="operationtask",
            name="task_project",
            field=models.ForeignKey(
                default="---",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="operations_task_project",
                to="operations.operationproject",
            ),
        ),
    ]
