# Generated by Django 4.1.5 on 2023-02-20 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0008_remove_servicecategory_service_and_more"),
        ("operations", "0002_alter_operationcontract_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operationtask",
            name="task_category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="operations_task_service_category",
                to="settings.servicecategory",
            ),
        ),
    ]
