# Generated by Django 4.1.5 on 2023-02-23 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("human_resource", "0020_employee_branch"),
        ("customer", "0008_alter_customer_country"),
        ("settings", "0012_delete_gallerytest"),
        ("operations", "0003_alter_operationtask_task_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="operationproject",
            old_name="name",
            new_name="project_id",
        ),
        migrations.AddField(
            model_name="operationproject",
            name="budget",
            field=models.CharField(max_length=150, null=True, verbose_name="budget(N)"),
        ),
        migrations.AddField(
            model_name="operationproject",
            name="client",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="customer.customer",
            ),
        ),
        migrations.AddField(
            model_name="operationproject",
            name="department",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_department",
                to="human_resource.department",
            ),
        ),
        migrations.AddField(
            model_name="operationproject",
            name="expected_end_date",
            field=models.DateField(
                default="2023-03-02", verbose_name="end date(deadline)"
            ),
        ),
        migrations.AddField(
            model_name="operationproject",
            name="hour_estimated",
            field=models.TimeField(default="00:00:00", null=True),
        ),
        migrations.AddField(
            model_name="operationproject",
            name="project_category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="settings.servicecategory",
            ),
        ),
        migrations.AddField(
            model_name="operationproject",
            name="project_desciption",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="operationproject",
            name="project_name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="operationproject",
            name="project_owner",
            field=models.CharField(
                help_text="Please Enter Unique Id.", max_length=150, null=True
            ),
        ),
        migrations.AddField(
            model_name="operationproject",
            name="start_date",
            field=models.DateField(default="2023-03-02"),
        ),
    ]
