# Generated by Django 4.1.5 on 2023-02-23 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("human_resource", "0020_employee_branch"),
        ("operations", "0004_rename_name_operationproject_project_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="operationproject",
            name="project_members",
            field=models.ManyToManyField(null=True, to="human_resource.employee"),
        ),
    ]
