# Generated by Django 4.1.5 on 2023-02-26 17:17

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0008_alter_customer_country"),
        ("settings", "0012_delete_gallerytest"),
        ("operations", "0005_operationproject_project_members"),
    ]

    operations = [
        migrations.RenameField(
            model_name="operationsite",
            old_name="name",
            new_name="site_name",
        ),
        migrations.AddField(
            model_name="operationproject",
            name="status",
            field=models.CharField(
                choices=[
                    ("completed", "Completed"),
                    ("rejected", "Rejected"),
                    ("pending", "Pending"),
                ],
                max_length=150,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="operationsite",
            name="date_creation",
            field=models.DateField(default="2023-03-02"),
        ),
        migrations.AddField(
            model_name="operationsite",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_site_related",
                to="operations.operationproject",
            ),
        ),
        migrations.AddField(
            model_name="operationsite",
            name="scope_of_work",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="operationsite",
            name="service_category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="settings.servicecategory",
            ),
        ),
        migrations.AddField(
            model_name="operationsite",
            name="site_client",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="customer.customer",
            ),
        ),
        migrations.AddField(
            model_name="operationsite",
            name="site_country",
            field=django_countries.fields.CountryField(default="---", max_length=250),
        ),
        migrations.AddField(
            model_name="operationsite",
            name="site_lga",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="operationsite",
            name="site_map_location",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="operationsite",
            name="site_state",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="operationsite",
            name="status",
            field=models.CharField(
                choices=[
                    ("completed", "Completed"),
                    ("rejected", "Rejected"),
                    ("pending", "Pending"),
                ],
                max_length=150,
                null=True,
            ),
        ),
    ]
