# Generated by Django 4.1.5 on 2023-02-26 18:08

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0006_rename_name_operationsite_site_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="operationcontract",
            old_name="name",
            new_name="contract_title",
        ),
        migrations.AddField(
            model_name="operationcontract",
            name="address",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="operationcontract",
            name="alternative_address",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="operationcontract",
            name="city",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="operationcontract",
            name="contractor_phone",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="operationcontract",
            name="country",
            field=django_countries.fields.CountryField(default="---", max_length=250),
        ),
        migrations.AddField(
            model_name="operationcontract",
            name="expected_end_date",
            field=models.DateField(
                default="2023-03-02", verbose_name="end date(deadline)"
            ),
        ),
        migrations.AddField(
            model_name="operationcontract",
            name="fullname",
            field=models.CharField(
                max_length=150, null=True, verbose_name="fullname or cooperate name"
            ),
        ),
        migrations.AddField(
            model_name="operationcontract",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="operations.operationproject",
            ),
        ),
        migrations.AddField(
            model_name="operationcontract",
            name="project_description",
            field=models.TextField(null=True, verbose_name="Project Scope Description"),
        ),
        migrations.AddField(
            model_name="operationcontract",
            name="project_type",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="operationcontract",
            name="project_value",
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="operationcontract",
            name="site",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="operations.operationsite",
            ),
        ),
        migrations.AddField(
            model_name="operationcontract",
            name="start_date",
            field=models.DateField(default="2023-03-02"),
        ),
        migrations.AddField(
            model_name="operationcontract",
            name="state",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="operationcontract",
            name="status",
            field=models.CharField(
                choices=[
                    ("completed", "Completed"),
                    ("rejected", "Rejected"),
                    ("pending", "Pending"),
                ],
                max_length=150,
                null=True,
            ),
        ),
    ]
