# Generated by Django 4.1.5 on 2023-02-26 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0007_rename_name_operationcontract_contract_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operationcontract",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="operations.operationproject",
            ),
        ),
        migrations.AlterField(
            model_name="operationcontract",
            name="site",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="operations.operationsite",
            ),
        ),
        migrations.AlterField(
            model_name="operationsite",
            name="site_lga",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Site Local Government"
            ),
        ),
    ]
