# Generated by Django 4.1.5 on 2023-02-26 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0008_alter_operationcontract_project_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="operationcontract",
            name="code",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="operationproject",
            name="code",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="operationsite",
            name="code",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="operationtask",
            name="code",
            field=models.CharField(max_length=150, null=True),
        ),
    ]
