# Generated by Django 4.1.5 on 2023-03-01 18:29

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0009_operationcontract_code_operationproject_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="operationtask",
            name="country",
            field=django_countries.fields.CountryField(
                blank=True, max_length=150, null=True
            ),
        ),
        migrations.AddField(
            model_name="operationtask",
            name="lga",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="operationtask",
            name="scope_of_work",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="operationtask",
            name="site_map_location",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="operationtask",
            name="state",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="operationtask",
            name="task_dependency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_dependency_rel",
                to="operations.operationtask",
            ),
        ),
        migrations.AlterField(
            model_name="operationtask",
            name="task_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="operationtask",
            name="task_site",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_site_rel",
                to="operations.operationsite",
            ),
        ),
    ]
