# Generated by Django 4.1.5 on 2023-03-01 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0010_operationtask_country_operationtask_lga_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="operationcontract",
            old_name="project_description",
            new_name="contract_description",
        ),
        migrations.RenameField(
            model_name="operationcontract",
            old_name="project",
            new_name="contract_project",
        ),
        migrations.RenameField(
            model_name="operationcontract",
            old_name="site",
            new_name="contract_site",
        ),
        migrations.RenameField(
            model_name="operationcontract",
            old_name="project_type",
            new_name="contract_type",
        ),
        migrations.RemoveField(
            model_name="operationcontract",
            name="project_value",
        ),
        migrations.AddField(
            model_name="operationcontract",
            name="contract_dependency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="operations.operationcontract",
            ),
        ),
        migrations.AddField(
            model_name="operationcontract",
            name="contract_value",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="operationcontract",
            name="priority",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="operationproject",
            name="project_dependency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_dependencys",
                to="operations.operationproject",
            ),
        ),
        migrations.AddField(
            model_name="operationtask",
            name="task_time",
            field=models.TimeField(default="00:00:00"),
        ),
    ]
