# Generated by Django 4.1.5 on 2023-03-07 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0012_operationcontract_user_operationproject_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="operationtask",
            name="country",
        ),
        migrations.RemoveField(
            model_name="operationtask",
            name="lga",
        ),
        migrations.RemoveField(
            model_name="operationtask",
            name="scope_of_work",
        ),
        migrations.RemoveField(
            model_name="operationtask",
            name="site_map_location",
        ),
        migrations.RemoveField(
            model_name="operationtask",
            name="state",
        ),
    ]
