# Generated by Django 4.1.5 on 2023-03-08 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0017_alter_operationcontract_contract_value_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="operationcontract",
            name="contract_value_currency",
        ),
        migrations.AlterField(
            model_name="operationcontract",
            name="contract_value",
            field=models.CharField(max_length=500, null=True),
        ),
    ]
