# Generated by Django 4.1.5 on 2023-03-10 14:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0006_reportingsheet_modelid_reportingsheet_modelname"),
        ("operations", "0022_contractreport"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneralReport",
            fields=[
                (
                    "reportingsheet_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="reports.reportingsheet",
                    ),
                ),
                ("task_title", models.CharField(max_length=150, null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("incomplete", "Incomplete"),
                            ("to_do", "To Do"),
                            ("redo", "Redo"),
                            ("done", "Done"),
                            ("completed", "Completed"),
                        ],
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "due_date",
                    models.DateField(
                        default=datetime.datetime(2023, 3, 10, 14, 25, 35, 876980)
                    ),
                ),
                (
                    "task_start_date",
                    models.DateField(
                        default=datetime.datetime(2023, 3, 10, 14, 25, 35, 876997)
                    ),
                ),
                ("comment", models.TextField()),
            ],
            bases=("reports.reportingsheet",),
        ),
        migrations.DeleteModel(
            name="ContractReport",
        ),
    ]
