# Generated by Django 4.1.5 on 2023-03-10 16:31

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0024_alter_generalreport_due_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="landsurveyreport",
            name="survey_equipment",
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name="engineeringreport",
            name="site_date",
            field=models.DateField(
                default=datetime.datetime(2023, 3, 10, 16, 31, 53, 90910)
            ),
        ),
        migrations.AlterField(
            model_name="generalreport",
            name="due_date",
            field=models.DateField(
                default=datetime.datetime(2023, 3, 10, 16, 31, 53, 89849)
            ),
        ),
        migrations.AlterField(
            model_name="generalreport",
            name="task_start_date",
            field=models.DateField(
                default=datetime.datetime(2023, 3, 10, 16, 31, 53, 89865)
            ),
        ),
        migrations.RemoveField(
            model_name="landsurveyreport",
            name="proposed_activity",
        ),
        migrations.RemoveField(
            model_name="landsurveyreport",
            name="site_activities",
        ),
        migrations.AlterField(
            model_name="landsurveyreport",
            name="site_date",
            field=models.DateField(
                default=datetime.datetime(2023, 3, 10, 16, 31, 53, 95443)
            ),
        ),
        migrations.AlterField(
            model_name="landsurveyreport",
            name="site_point_records",
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name="landsurveyreport",
            name="proposed_activity",
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name="landsurveyreport",
            name="site_activities",
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
