# Generated by Django 4.1.5 on 2023-03-10 17:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0025_landsurveyreport_survey_equipment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="engineeringreport",
            name="description",
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
