# Generated by Django 4.1.5 on 2023-03-10 17:00

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0026_alter_engineeringreport_description"),
        ("settings", "0016_laborbillquotation_quotation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="engineeringreport",
            name="labor_and_bill",
            field=models.ManyToManyField(
                related_name="eng_bill_rel", to="settings.laborbillquotation"
            ),
        ),
        migrations.AlterField(
            model_name="engineeringreport",
            name="material_received",
            field=models.ManyToManyField(
                related_name="eng_material_needed",
                to="settings.quotation",
                verbose_name="material received and time",
            ),
        ),
        migrations.AlterField(
            model_name="engineeringreport",
            name="materials_needed",
            field=models.ManyToManyField(
                related_name="eng_material_rel", to="settings.quotation"
            ),
        ),
        migrations.RemoveField(
            model_name="engineeringreport",
            name="proposed_activity",
        ),
        migrations.RemoveField(
            model_name="engineeringreport",
            name="site_activities",
        ),
        migrations.AlterField(
            model_name="engineeringreport",
            name="site_date",
            field=models.DateField(
                default=datetime.datetime(2023, 3, 10, 17, 0, 17, 918007)
            ),
        ),
        migrations.AlterField(
            model_name="generalreport",
            name="due_date",
            field=models.DateField(
                default=datetime.datetime(2023, 3, 10, 17, 0, 17, 916979)
            ),
        ),
        migrations.AlterField(
            model_name="generalreport",
            name="task_start_date",
            field=models.DateField(
                default=datetime.datetime(2023, 3, 10, 17, 0, 17, 916994)
            ),
        ),
        migrations.AlterField(
            model_name="landsurveyreport",
            name="equipment",
            field=models.ManyToManyField(
                related_name="land_equipment_rel",
                to="settings.quotation",
                verbose_name="Surveying Expenditure on Labour",
            ),
        ),
        migrations.AlterField(
            model_name="landsurveyreport",
            name="labor_and_bill",
            field=models.ManyToManyField(
                related_name="land_bills_rel", to="settings.laborbillquotation"
            ),
        ),
        migrations.AlterField(
            model_name="landsurveyreport",
            name="material_received",
            field=models.ManyToManyField(
                related_name="land_survey_rel",
                to="settings.quotation",
                verbose_name="material received and time",
            ),
        ),
        migrations.AlterField(
            model_name="landsurveyreport",
            name="materials_needed",
            field=models.ManyToManyField(
                related_name="land_material_need", to="settings.quotation"
            ),
        ),
        migrations.AlterField(
            model_name="landsurveyreport",
            name="site_date",
            field=models.DateField(
                default=datetime.datetime(2023, 3, 10, 17, 0, 17, 921316)
            ),
        ),
        migrations.AddField(
            model_name="engineeringreport",
            name="proposed_activity",
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name="engineeringreport",
            name="site_activities",
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
