# Generated by Django 4.1.5 on 2023-03-10 17:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0017_delete_activities"),
        ("operations", "0027_alter_engineeringreport_labor_and_bill_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="engineeringreport",
            name="labor_and_bill",
        ),
        migrations.RemoveField(
            model_name="engineeringreport",
            name="material_received",
        ),
        migrations.RemoveField(
            model_name="engineeringreport",
            name="materials_needed",
        ),
        migrations.AlterField(
            model_name="engineeringreport",
            name="site_date",
            field=models.DateField(
                default=datetime.datetime(2023, 3, 10, 17, 19, 10, 300415)
            ),
        ),
        migrations.AlterField(
            model_name="generalreport",
            name="due_date",
            field=models.DateField(
                default=datetime.datetime(2023, 3, 10, 17, 19, 10, 299350)
            ),
        ),
        migrations.AlterField(
            model_name="generalreport",
            name="task_start_date",
            field=models.DateField(
                default=datetime.datetime(2023, 3, 10, 17, 19, 10, 299366)
            ),
        ),
        migrations.RemoveField(
            model_name="landsurveyreport",
            name="equipment",
        ),
        migrations.RemoveField(
            model_name="landsurveyreport",
            name="labor_and_bill",
        ),
        migrations.RemoveField(
            model_name="landsurveyreport",
            name="material_received",
        ),
        migrations.RemoveField(
            model_name="landsurveyreport",
            name="materials_needed",
        ),
        migrations.AlterField(
            model_name="landsurveyreport",
            name="site_date",
            field=models.DateField(
                default=datetime.datetime(2023, 3, 10, 17, 19, 10, 302049)
            ),
        ),
        migrations.AddField(
            model_name="engineeringreport",
            name="labor_and_bill",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="eng_bill_rel",
                to="settings.laborbillquotation",
            ),
        ),
        migrations.AddField(
            model_name="engineeringreport",
            name="material_received",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="eng_material_needed",
                to="settings.quotation",
                verbose_name="material received and time",
            ),
        ),
        migrations.AddField(
            model_name="engineeringreport",
            name="materials_needed",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="eng_material_rel",
                to="settings.quotation",
            ),
        ),
        migrations.AddField(
            model_name="landsurveyreport",
            name="equipment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="land_equipment_rel",
                to="settings.quotation",
                verbose_name="Surveying Expenditure on Labour",
            ),
        ),
        migrations.AddField(
            model_name="landsurveyreport",
            name="labor_and_bill",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="land_bills_rel",
                to="settings.laborbillquotation",
            ),
        ),
        migrations.AddField(
            model_name="landsurveyreport",
            name="material_received",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="land_survey_rel",
                to="settings.quotation",
                verbose_name="material received and time",
            ),
        ),
        migrations.AddField(
            model_name="landsurveyreport",
            name="materials_needed",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="land_material_need",
                to="settings.quotation",
            ),
        ),
    ]
