# Generated by Django 4.1.5 on 2023-03-10 17:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0028_remove_engineeringreport_labor_and_bill_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="engineeringreport",
            name="site_date",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 3, 10, 17, 24, 14, 505575, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="generalreport",
            name="due_date",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 3, 10, 17, 24, 14, 504476, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="generalreport",
            name="task_start_date",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 3, 10, 17, 24, 14, 504494, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="landsurveyreport",
            name="site_date",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 3, 10, 17, 24, 14, 507312, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
