# Generated by Django 4.1.5 on 2023-03-10 17:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0030_alter_engineeringreport_site_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generalreport",
            name="due_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="generalreport",
            name="task_start_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="landsurveyreport",
            name="site_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
