# Generated by Django 4.1.5 on 2023-03-10 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("human_resource", "0036_alter_employee_skills"),
        ("operations", "0031_alter_generalreport_due_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operationproject",
            name="project_members",
            field=models.ManyToManyField(to="human_resource.employee"),
        ),
    ]
