# Generated by Django 4.1.5 on 2023-03-10 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0032_alter_operationproject_project_members"),
    ]

    operations = [
        migrations.RenameField(
            model_name="generalreport",
            old_name="comment",
            new_name="report_comment",
        ),
        migrations.RenameField(
            model_name="generalreport",
            old_name="due_date",
            new_name="report_date",
        ),
        migrations.RemoveField(
            model_name="engineeringreport",
            name="client",
        ),
        migrations.RemoveField(
            model_name="engineeringreport",
            name="project_title",
        ),
        migrations.RemoveField(
            model_name="engineeringreport",
            name="site_activities",
        ),
        migrations.RemoveField(
            model_name="engineeringreport",
            name="site_date",
        ),
        migrations.RemoveField(
            model_name="engineeringreport",
            name="site_location",
        ),
        migrations.RemoveField(
            model_name="engineeringreport",
            name="state_of_site",
        ),
        migrations.RemoveField(
            model_name="generalreport",
            name="task_start_date",
        ),
        migrations.RemoveField(
            model_name="generalreport",
            name="task_title",
        ),
        migrations.RemoveField(
            model_name="landsurveyreport",
            name="project_title",
        ),
        migrations.RemoveField(
            model_name="landsurveyreport",
            name="site_date",
        ),
        migrations.RemoveField(
            model_name="landsurveyreport",
            name="site_location",
        ),
        migrations.AddField(
            model_name="engineeringreport",
            name="report_sites",
            field=models.ManyToManyField(
                related_name="engeering_site_rel", to="operations.operationsite"
            ),
        ),
        migrations.AddField(
            model_name="generalreport",
            name="report_tasks",
            field=models.ManyToManyField(
                related_name="general_report_rel", to="operations.operationtask"
            ),
        ),
        migrations.AddField(
            model_name="landsurveyreport",
            name="report_sites",
            field=models.ManyToManyField(
                related_name="engineering_sites_rel", to="operations.operationsite"
            ),
        ),
    ]
