# Generated by Django 4.1.5 on 2023-03-10 18:48

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0033_rename_comment_generalreport_report_comment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generalreport",
            name="report_comment",
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name="generalreport",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("incomplete", "Incomplete"),
                    ("to_do", "To Do"),
                    ("redo", "Redo"),
                    ("doing", "Doing"),
                    ("completed", "Completed"),
                ],
                max_length=150,
                null=True,
            ),
        ),
    ]
