# Generated by Django 4.1.5 on 2023-03-13 14:21

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0034_alter_generalreport_report_comment_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuotesModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_address", models.CharField(max_length=150, null=True)),
                ("phone_number", models.CharField(max_length=150, null=True)),
                ("service", models.CharField(max_length=150, null=True)),
                ("message", ckeditor.fields.RichTextField()),
            ],
            options={
                "verbose_name": "Quote",
                "verbose_name_plural": "Quotes",
            },
        ),
    ]
