# Generated by Django 4.1.5 on 2023-03-13 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0017_delete_activities"),
        ("operations", "0036_quotesmodel_service_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quotesmodel",
            name="full_name",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="operationtask",
            name="task_category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="operations_task_service_category",
                to="settings.service",
            ),
        ),
    ]
