# Generated by Django 4.1.5 on 2023-03-15 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0017_delete_activities"),
        ("operations", "0037_quotesmodel_full_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operationproject",
            name="project_category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="settings.service",
            ),
        ),
        migrations.AlterField(
            model_name="operationsite",
            name="service_category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="settings.service",
            ),
        ),
        migrations.AlterField(
            model_name="quotesmodel",
            name="service_category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service_category_rel",
                to="settings.service",
            ),
        ),
    ]
