# Generated by Django 4.1.5 on 2023-03-15 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0038_alter_operationproject_project_category_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quotesmodel",
            name="service_category",
        ),
    ]
