# Generated by Django 4.1.5 on 2023-03-18 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("authuser", "0026_branchaccessories_value_of_asset_currency_and_more"),
        ("operations", "0039_remove_quotesmodel_service_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="operationtask",
            name="branch",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_related_branch",
                to="authuser.branch",
            ),
        ),
    ]
