# Generated by Django 4.1.5 on 2023-03-18 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0040_operationtask_branch"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="operationtask",
            options={
                "permissions": (("can_view_table_actions", "Can View Table Actions"),),
                "verbose_name": "Task",
                "verbose_name_plural": "Tasks",
            },
        ),
    ]
