# Generated by Django 4.1.5 on 2023-03-18 16:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("human_resource", "0038_delete_appointment"),
        ("authuser", "0026_branchaccessories_value_of_asset_currency_and_more"),
        ("operations", "0042_appointment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stores",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PayRoll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bonus", models.IntegerField()),
                ("monthly_amount", models.IntegerField()),
                ("monthly_date", models.DateField(default=django.utils.timezone.now)),
                ("created", models.DateField()),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payroll_related",
                        to="authuser.branch",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payroll_employee_rel",
                        to="human_resource.employee",
                    ),
                ),
            ],
        ),
    ]
