# Generated by Django 4.1.5 on 2023-03-18 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0043_stores_payroll"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payroll",
            name="bonus",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="monthly_amount",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
