# Generated by Django 4.1.5 on 2023-03-23 13:45

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0025_servicecalculator_name"),
        ("operations", "0044_alter_payroll_bonus_alter_payroll_monthly_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="engineeringreport",
            name="report_date",
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name="engineeringreport",
            name="site_activities",
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name="stores",
            name="name",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="stores",
            name="site",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="store_site_related",
                to="operations.operationsite",
            ),
        ),
        migrations.RemoveField(
            model_name="engineeringreport",
            name="labor_and_bill",
        ),
        migrations.RemoveField(
            model_name="engineeringreport",
            name="material_received",
        ),
        migrations.RemoveField(
            model_name="engineeringreport",
            name="materials_needed",
        ),
        migrations.AlterField(
            model_name="engineeringreport",
            name="report_sites",
            field=models.ManyToManyField(to="operations.operationsite"),
        ),
        migrations.AddField(
            model_name="engineeringreport",
            name="labor_and_bill",
            field=models.ManyToManyField(to="settings.laborbillquotation"),
        ),
        migrations.AddField(
            model_name="engineeringreport",
            name="material_received",
            field=models.ManyToManyField(
                to="settings.quotation", verbose_name="material received and time"
            ),
        ),
        migrations.AddField(
            model_name="engineeringreport",
            name="materials_needed",
            field=models.ManyToManyField(
                related_name="eng_material_rel", to="settings.quotation"
            ),
        ),
    ]
