# Generated by Django 4.1.5 on 2023-03-23 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0046_alter_stores_options_remove_stores_site_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stores",
            name="site",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="store_site",
                to="operations.operationsite",
            ),
        ),
        migrations.AlterField(
            model_name="engineeringreport",
            name="materials_needed",
            field=models.ManyToManyField(
                related_name="eng_material_rel", to="operations.stores"
            ),
        ),
    ]
