# Generated by Django 4.1.5 on 2023-03-23 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0048_storeexpenditure"),
    ]

    operations = [
        migrations.AddField(
            model_name="engineeringreport",
            name="material_used",
            field=models.ManyToManyField(to="operations.storeexpenditure"),
        ),
        migrations.AlterField(
            model_name="engineeringreport",
            name="material_received",
            field=models.ManyToManyField(
                to="operations.stores", verbose_name="material received and time"
            ),
        ),
    ]
