# Generated by Django 4.1.5 on 2023-03-23 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0049_engineeringreport_material_used_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="storeexpenditure",
            name="unity_price",
        ),
        migrations.RemoveField(
            model_name="storeexpenditure",
            name="unity_price_currency",
        ),
    ]
