# Generated by Django 4.1.5 on 2023-03-23 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0050_remove_storeexpenditure_unity_price_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stores",
            old_name="unity_price",
            new_name="unit_price",
        ),
        migrations.RenameField(
            model_name="stores",
            old_name="unity_price_currency",
            new_name="unit_price_currency",
        ),
    ]
