# Generated by Django 4.1.5 on 2023-03-25 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0051_rename_unity_price_stores_unit_price_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DrawingBank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=200)),
                ("title", models.CharField(max_length=150)),
                ("description", models.TextField()),
                ("created", models.DateField(auto_now=True)),
            ],
            options={
                "verbose_name": "Drawing Bank",
                "verbose_name_plural": "Drawing Bank",
            },
        ),
    ]
