# Generated by Django 4.1.5 on 2023-03-25 11:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0052_drawingbank"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="appointment_date",
            field=models.DateField(
                default=django.utils.timezone.now,
                error_messages="Appointment Date Taken",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="email",
            field=models.EmailField(max_length=150, verbose_name="Client Email"),
        ),
    ]
