# Generated by Django 4.1.5 on 2023-03-25 11:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0053_alter_appointment_appointment_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="appointment_time",
        ),
        migrations.AlterField(
            model_name="appointment",
            name="appointment_date",
            field=models.DateTimeField(
                default=datetime.datetime.now,
                error_messages="Appointment time and date already taken.",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="name",
            field=models.CharField(max_length=150, verbose_name="Client Name"),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="phone",
            field=models.CharField(max_length=150, verbose_name="client Phone"),
        ),
    ]
