# Generated by Django 4.1.5 on 2023-03-25 12:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0054_remove_appointment_appointment_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="appointment_date",
            field=models.DateTimeField(default=datetime.datetime.now, unique=True),
        ),
    ]
