# Generated by Django 4.1.5 on 2023-03-25 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("human_resource", "0039_delete_drawingbank"),
        ("operations", "0055_alter_appointment_appointment_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="designation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointment_designation",
                to="human_resource.designation",
            ),
        ),
    ]
