# Generated by Django 4.1.5 on 2023-03-25 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("human_resource", "0039_delete_drawingbank"),
        ("operations", "0056_appointment_designation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="designation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointment_designation",
                to="human_resource.designation",
            ),
        ),
    ]
