# Generated by Django 4.1.5 on 2023-03-25 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0058_appointment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="code",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
