# Generated by Django 4.1.5 on 2023-03-25 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0059_appointment_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="operationproject",
            name="hour_estimated",
        ),
        migrations.RemoveField(
            model_name="operationproject",
            name="project_owner",
        ),
    ]
