# Generated by Django 4.1.5 on 2023-03-25 17:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0061_remove_engineeringreport_report_sites_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stores",
            name="date_time",
            field=models.CharField(default=datetime.datetime.now, max_length=150),
        ),
    ]
