# Generated by Django 4.1.5 on 2023-03-25 18:20

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0062_alter_stores_date_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="engineeringreport",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending")], default="pending", max_length=150
            ),
        ),
        migrations.AlterField(
            model_name="engineeringreport",
            name="expenditure2",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2,
                default_currency="NGN",
                max_digits=10,
                null=True,
                verbose_name="Expenditure On Materials Received",
            ),
        ),
        migrations.AlterField(
            model_name="stores",
            name="date_time",
            field=models.CharField(default="", max_length=150),
        ),
    ]
