# Generated by Django 4.1.5 on 2023-03-25 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0063_engineeringreport_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="operationsite",
            name="stores",
            field=models.ManyToManyField(to="operations.stores"),
        ),
    ]
