# Generated by Django 4.1.5 on 2023-03-25 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0064_operationsite_stores"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stores",
            name="site",
        ),
    ]
