# Generated by Django 4.1.5 on 2023-03-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0066_operationsite_site_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operationsite",
            name="stores",
            field=models.ManyToManyField(
                related_name="site_store_rel", to="operations.stores"
            ),
        ),
    ]
