# Generated by Django 4.1.5 on 2023-03-27 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0067_alter_operationsite_stores"),
    ]

    operations = [
        migrations.AddField(
            model_name="stores",
            name="is_site_taken",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="stores",
            name="site_code",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
