# Generated by Django 4.1.5 on 2023-03-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0068_stores_is_site_taken_stores_site_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operationsite",
            name="stores",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="site_store_rel",
                to="operations.stores",
            ),
        ),
    ]
