# Generated by Django 4.1.5 on 2023-03-29 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("human_resource", "0039_delete_drawingbank"),
        ("operations", "0071_alter_operationtask_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operationtask",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="operation_rel",
                to="human_resource.employee",
            ),
        ),
    ]
