# Generated by Django 4.1.5 on 2023-03-29 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("human_resource", "0039_delete_drawingbank"),
        ("operations", "0073_alter_operationtask_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operationproject",
            name="project_members",
            field=models.ManyToManyField(
                related_name="project_members_rel", to="human_resource.employee"
            ),
        ),
    ]
