# Generated by Django 4.1.5 on 2023-03-29 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("human_resource", "0039_delete_drawingbank"),
        ("customer", "0009_customer_code"),
        ("operations", "0074_alter_operationproject_project_members"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operationproject",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="client_rel",
                to="customer.customer",
            ),
        ),
        migrations.AlterField(
            model_name="operationproject",
            name="project_members",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="project_members_rel",
                to="human_resource.employee",
            ),
        ),
    ]
