# Generated by Django 4.1.5 on 2023-03-29 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0009_customer_code"),
        ("operations", "0075_alter_operationproject_client_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operationsite",
            name="site_client",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="site_client_rel",
                to="customer.customer",
            ),
        ),
    ]
