# Generated by Django 4.1.5 on 2023-04-12 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0034_alter_servicecalculator_function"),
        ("operations", "0076_alter_operationsite_site_client"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="quotesmodel",
            options={"verbose_name": "Quotation", "verbose_name_plural": "Quotations"},
        ),
        migrations.RemoveField(
            model_name="quotesmodel",
            name="message",
        ),
        migrations.RemoveField(
            model_name="quotesmodel",
            name="service",
        ),
        migrations.AddField(
            model_name="quotesmodel",
            name="nb",
            field=models.IntegerField(default=0, verbose_name="Number of bedroom"),
        ),
        migrations.AddField(
            model_name="quotesmodel",
            name="nf",
            field=models.IntegerField(default=0, verbose_name="Number of floor"),
        ),
        migrations.AddField(
            model_name="quotesmodel",
            name="services",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Service_calculator_rel",
                to="settings.servicecalculator",
            ),
        ),
        migrations.AddField(
            model_name="quotesmodel",
            name="status",
            field=models.CharField(
                choices=[
                    (100, "Pending"),
                    (200, "Mininium Of 70 Percent"),
                    (300, "Payment Completed"),
                ],
                default=100,
                max_length=150,
            ),
        ),
    ]
