# Generated by Django 4.1.5 on 2023-04-12 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "operations",
            "0077_alter_quotesmodel_options_remove_quotesmodel_message_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="quotesmodel",
            options={
                "verbose_name": "Service Quotes",
                "verbose_name_plural": "Service Quotess",
            },
        ),
        migrations.AlterField(
            model_name="quotesmodel",
            name="status",
            field=models.CharField(
                choices=[
                    ("100", "Pending"),
                    ("200", "Mininium Of 70 Percent"),
                    ("300", "Payment Completed"),
                ],
                default="100",
                max_length=150,
            ),
        ),
    ]
