# Generated by Django 4.1.5 on 2023-04-12 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0078_alter_quotesmodel_options_alter_quotesmodel_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="quotesmodel",
            name="total",
            field=models.IntegerField(default=0),
        ),
    ]
