# Generated by Django 4.1.5 on 2023-04-12 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0009_customer_code"),
        ("operations", "0079_quotesmodel_total"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="quotesmodel",
            options={
                "verbose_name": "Service Quotes",
                "verbose_name_plural": "Service Quotes",
            },
        ),
        migrations.RenameField(
            model_name="quotesmodel",
            old_name="email_address",
            new_name="code",
        ),
        migrations.RemoveField(
            model_name="quotesmodel",
            name="full_name",
        ),
        migrations.RemoveField(
            model_name="quotesmodel",
            name="phone_number",
        ),
        migrations.AddField(
            model_name="quotesmodel",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer_quote_rel",
                to="customer.customer",
            ),
        ),
    ]
