# Generated by Django 4.1.5 on 2023-04-12 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0009_customer_code"),
        ("operations", "0080_alter_quotesmodel_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quotesmodel",
            name="amount_deposited",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="quotesmodel",
            name="amount_pending",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="quotesmodel",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer_quote_rel",
                to="customer.customer",
                verbose_name="Client",
            ),
        ),
    ]
