# Generated by Django 4.1.5 on 2023-04-12 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0081_quotesmodel_amount_deposited_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quotesmodel",
            name="amount_deposited",
            field=models.IntegerField(
                blank=True,
                default=0,
                null=True,
                verbose_name="Amount Deposited (70 Percent)",
            ),
        ),
        migrations.AlterField(
            model_name="quotesmodel",
            name="amount_pending",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="Amount Remaining"
            ),
        ),
    ]
