# Generated by Django 4.1.5 on 2023-04-12 14:39

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0082_alter_quotesmodel_amount_deposited_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quotesmodel",
            name="comment",
            field=ckeditor.fields.RichTextField(default="Comment"),
        ),
        migrations.AddField(
            model_name="quotesmodel",
            name="ns",
            field=models.IntegerField(default=0, verbose_name="Number of sitting room"),
        ),
    ]
