# Generated by Django 4.1.5 on 2023-04-19 14:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("operations", "0084_alter_quotesmodel_comment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appointment",
            options={
                "permissions": (
                    ("can_view_appointment_details", "can view appointment details"),
                ),
                "verbose_name": "Appointment",
                "verbose_name_plural": "Appointments",
            },
        ),
        migrations.AddField(
            model_name="appointment",
            name="end_date",
            field=models.TimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name="appointment",
            name="start_date",
            field=models.TimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name="appointment",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointment_user_rel",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
