# Generated by Django 4.1.5 on 2023-04-20 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0085_alter_appointment_options_appointment_end_date_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appointment",
            options={
                "permissions": (
                    ("can_view_appointment_details", "can view appointment details"),
                    ("can_perform_extra_action", "Can perform extra action"),
                ),
                "verbose_name": "Appointment",
                "verbose_name_plural": "Appointments",
            },
        ),
    ]
