# Generated by Django 4.1.5 on 2023-04-21 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0086_alter_appointment_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="generalreport",
            name="report_tasks",
        ),
        migrations.RemoveField(
            model_name="generalreport",
            name="reportingsheet_ptr",
        ),
        migrations.RemoveField(
            model_name="landsurveyreport",
            name="equipment",
        ),
        migrations.RemoveField(
            model_name="landsurveyreport",
            name="labor_and_bill",
        ),
        migrations.RemoveField(
            model_name="landsurveyreport",
            name="material_received",
        ),
        migrations.RemoveField(
            model_name="landsurveyreport",
            name="materials_needed",
        ),
        migrations.RemoveField(
            model_name="landsurveyreport",
            name="report_sites",
        ),
        migrations.RemoveField(
            model_name="landsurveyreport",
            name="reportingsheet_ptr",
        ),
        migrations.AlterModelOptions(
            name="operationtask",
            options={
                "permissions": (
                    ("can_access_engineering_report", "Can Access Engineering Report"),
                    ("can_access_survey_report", "Can Access Survey Report"),
                    ("can_access_landing_report", "Can Access Landing Report"),
                ),
                "verbose_name": "Task",
                "verbose_name_plural": "Tasks",
            },
        ),
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("finished", "Finished"),
                    ("cancelled", "cancelled"),
                ],
                default="pending",
                max_length=150,
                null=True,
            ),
        ),
        migrations.DeleteModel(
            name="EngineeringReport",
        ),
        migrations.DeleteModel(
            name="GeneralReport",
        ),
        migrations.DeleteModel(
            name="LandSurveyReport",
        ),
    ]
