# Generated by Django 4.1.5 on 2023-04-24 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0087_remove_generalreport_report_tasks_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="operationtask",
            name="status",
            field=models.CharField(
                choices=[
                    ("todo", "Todo"),
                    ("doing", "Doing"),
                    ("completed", "Completed"),
                    ("redo", "Redo"),
                    ("suspended", "Suspended"),
                ],
                default="todo",
                max_length=150,
            ),
        ),
        migrations.AlterField(
            model_name="quotesmodel",
            name="status",
            field=models.CharField(
                choices=[
                    ("100", "Pending"),
                    ("200", "Mininium Of 70 Percent"),
                    ("300", "Payment Completed"),
                    ("400", "Payment was rejected"),
                ],
                default="100",
                max_length=150,
            ),
        ),
    ]
