# Generated by Django 4.1.5 on 2023-04-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0088_operationtask_status_alter_quotesmodel_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="operationtask",
            name="report_message",
            field=models.TextField(blank=True, null=True),
        ),
    ]
