# Generated by Django 4.2.1 on 2023-12-28 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=150, null=True)),
                ('country', django_countries.fields.CountryField(default='---', max_length=250)),
                ('local_government', models.CharField(default='---', max_length=200)),
                ('town', models.CharField(default='---', max_length=200)),
                ('current_address', models.CharField(default='---', max_length=200)),
                ('permanent_address', models.CharField(default='---', max_length=200)),
                ('phone', models.CharField(default='---', max_length=200)),
                ('state', models.CharField(default='---', max_length=200)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], default='---', max_length=250)),
                ('notes', models.TextField(default='---')),
                ('create_at', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_relationship', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Client',
            },
        ),
    ]
