# Generated by Django 4.1.5 on 2023-02-09 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0002_customer_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={"verbose_name": "Client", "verbose_name_plural": "Client"},
        ),
    ]
