# Generated by Django 4.1.5 on 2023-02-03 22:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("authuser", "0003_branch"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("realestate", "0002_realestate_branch"),
    ]

    operations = [
        migrations.AddField(
            model_name="realestate",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_rel",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="realestate",
            name="branch",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="branch_rel",
                to="authuser.branch",
                verbose_name="Choose Branch",
            ),
        ),
    ]
