# Generated by Django 4.1.5 on 2023-02-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("realestate", "0005_alter_realestateplot_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="realestateplot",
            name="status",
            field=models.CharField(default="pending", max_length=500, null=True),
        ),
    ]
