# Generated by Django 4.1.5 on 2023-02-08 05:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("realestate", "0008_payment"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Payment",
            new_name="RealEstatePayment",
        ),
    ]
