# Generated by Django 4.1.5 on 2023-02-09 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0001_initial"),
        ("realestate", "0015_alter_realestateplot_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="realestatepayment",
            name="is_new_customer",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name="realestateplot",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer_realestate_plot_rel",
                to="customer.customer",
            ),
        ),
        migrations.AlterField(
            model_name="realestateplot",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("sold", "Sold"),
                    ("reserved", "Reserved"),
                    ("available", "Available"),
                ],
                default="available",
                max_length=500,
                null=True,
            ),
        ),
    ]
