# Generated by Django 4.1.5 on 2023-02-09 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("realestate", "0017_alter_realestateplot_payment_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="realestatepayment",
            name="is_payment_activated",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name="realestatepayment",
            name="purchase_code",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="realestateplot",
            name="has_ownership_changed",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
