# Generated by Django 4.1.5 on 2023-02-09 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("realestate", "0020_realestatepayment_proxy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="realestatepayment",
            name="total_amount",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
